name: Semantic Versioning

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'  
  workflow_dispatch:

jobs:
  versioning:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: run the versioning script file
      run: |
         chmod +x ./scripts/versioning.sh
         ./scripts/versioning.sh
      shell: bash
